### ISSUE TITLE
Console Error - Potentially with Levels Module

### ISSUE THREAD

**Issue by ncsululu** [dev7355608/perfect-vision#132]
VM5126:7 A: Error detected in module Perfect Vision.

This is *not* a libWrapper bug.

Find information about this module here: https://github.com/dev7355608/perfect-vision
Report this issue here: https://github.com/dev7355608/perfect-vision/issues

== Technical Details:
Detected by libWrapper.
Package ID= perfect-vision
Error= libWrapper: Can't wrap 'Levels.prototype.showOwnedTokensForPlayer', target does not exist or could not be found.

[Detected 1 package: perfect-vision]
    at new 🎁constructor (http://192.168.0.30:30000/modules/lib-wrapper/lib-wrapper.js:1:23802)
    at http://192.168.0.30:30000/modules/lib-wrapper/lib-wrapper.js:1:40318
    at ae (http://192.168.0.30:30000/modules/lib-wrapper/lib-wrapper.js:1:40351)
    at Function.🎁register [as register] (http://192.168.0.30:30000/modules/lib-wrapper/lib-wrapper.js:1:42916)
    at patch (http://192.168.0.30:30000/modules/perfect-vision/scripts/utils/patch.js:65:16)
    at http://192.168.0.30:30000/modules/perfect-vision/scripts/modules/levels/levels.js:106:5
    at Function._call (eval at <anonymous> (http://192.168.0.30:30000/modules/lib-wrapper/lib-wrapper.js:1:46143), <anonymous>:4:14)
    at Function.callAll (http://192.168.0.30:30000/scripts/foundry.js:153:12)
    at Game.initialize (http://192.168.0.30:30000/scripts/foundry.js:4274:11)
    at B.🎁call_wrapped [as call_wrapped] (http://192.168.0.30:30000/modules/lib-wrapper/lib-wrapper.js:1:27732)
    at Game.🎁libWrapperInit (http://192.168.0.30:30000/modules/lib-wrapper/lib-wrapper.js:1:47065)
_call @ VM5126:7

**Comment by Fraxinus1753** [comment]
I confirm there is a conflit with the Levels module. When Perfect vision is enabled, drawings and tokens appear under tiles that should appear underneath them (and thus are invisible). 

I am happy to provide additional details if needed.

**Comment by foxreinhold** [comment]
![image](https://user-images.githubusercontent.com/77173822/133505309-e7f6945e-e8ad-402d-b0ae-497496cfe132.png)



Just here to post the same thing

**Comment by dev7355608** [comment]
I released a fix with 2.9.8. If you notice more problems, let me know.
