### ISSUE TITLE
When perfect vision is enabled (and lib wrapper) cannot save core settings for default token

### ISSUE THREAD

**Issue by galaara98** [dev7355608/perfect-vision#195]
Foundry Stable 9.242
PF2E 3.1.3.9639
PV: 3.5.2
LibWrapper: 1.11.4.0

when only perfect vision is enabled (and lib wrapper)
I cannot save "Default Token Configuration" changes in the Core Settings

Console:
TypeError: document.getFlag is not a function
[Detected 1 package: perfect-vision]
    at config.js:68:40
    at Array.map (<anonymous>)
    at renderConfig (config.js:55:32)
    at Function._call (foundry.js:294:14)
    at Function.call (foundry.js:279:33)
    at DefaultTokenConfig._render (foundry.js:3114:13)
    at async DefaultTokenConfig._render (foundry.js:3761:5)
onError @ foundry.js:316
🎁call_wrapped @ libWrapper-wrapper.js:510
🎁Hooks.onError#lib-wrapper @ listeners.js:137
🎁Hooks.onError#0 @ libWrapper-wrapper.js:186
_call @ foundry.js:298
call @ foundry.js:279
_render @ foundry.js:3114
await in _render (async)
_render @ foundry.js:3761
render @ foundry.js:3018
render @ foundry.js:54532
_onClickSubmenu @ foundry.js:55345
dispatch @ jquery.min.js:2
v.handle @ jquery.min.js:2

Uncaught (in promise) TypeError: Cannot read properties of undefined (reading 'checked')
[Detected 2 packages: perfect-vision, lib-wrapper]
    at DefaultTokenConfig.<anonymous> (config.js:1036:76)
    at DefaultTokenConfig.wrapper (patch.js:17:25)
    at Z.🎁call_wrapper [as call_wrapper] (libWrapper-wrapper.js:619:16)
    at DefaultTokenConfig.🎁TokenConfig.prototype._getSubmitData#0 (libWrapper-wrapper.js:188:20)
    at DefaultTokenConfig._getSubmitData (foundry.js:54708:55)
    at DefaultTokenConfig._onSubmit (foundry.js:3840:27)
(anonymous) @ config.js:1036
wrapper @ patch.js:17
🎁call_wrapper @ libWrapper-wrapper.js:619
🎁TokenConfig.prototype._getSubmitData#0 @ libWrapper-wrapper.js:188
_getSubmitData @ foundry.js:54708
_onSubmit @ foundry.js:3840

**Comment by dev7355608** [comment]
This must have been broken since forever. Thanks for the report! Fixed in v3.5.3.
