### ISSUE TITLE
Incompatability with Scenery module

### ISSUE THREAD

**Issue by SamF111** [dev7355608/perfect-vision#204]
https://github.com/VanceCole/scenery
Scenery is a module that allows the GM to replace the background image of the scene easily. Examples of this may be for different weathers/times of day.

When used in combination with Perfect Vision, the following errors are thrown:

foundry.js:316 TypeError: Cannot read properties of null (reading 'draw')
[Detected 1 package: perfect-vision]
    at foundry.js:22074:25
    at EmbeddedCollection.map (common/utils/collection.mjs:145:24)
    at TokenLayer.draw (foundry.js:22072:32)
    at async Canvas.draw (foundry.js:19934:11)
    at async Canvas.🎁Canvas.prototype.draw#perfect-vision (modules/perfect-vision/scripts/core/canvas.js:359:9)
onError @ foundry.js:316
foundry.js:316 TypeError: Cannot read properties of null (reading 'draw')
[Detected 1 package: perfect-vision]
    at foundry.js:22074:25
    at EmbeddedCollection.map (common/utils/collection.mjs:145:24)
    at LightingLayer.draw (foundry.js:22072:32)
    at async LightingLayer.🎁LightingLayer.prototype.draw#perfect-vision (modules/perfect-vision/scripts/core/lighting.js:103:9)
    at async Canvas.draw (foundry.js:19934:11)
    at async Canvas.🎁Canvas.prototype.draw#perfect-vision (modules/perfect-vision/scripts/core/canvas.js:359:9)
onError @ foundry.js:316
foundry.js:316 TypeError: Cannot read properties of null (reading 'draw')
[Detected 1 package: perfect-vision]
    at foundry.js:22074:25
    at EmbeddedCollection.map (common/utils/collection.mjs:145:24)
    at NotesLayer.draw (foundry.js:22072:32)
    at async Canvas.draw (foundry.js:19934:11)
    at async Canvas.🎁Canvas.prototype.draw#perfect-vision (modules/perfect-vision/scripts/core/canvas.js:359:9)

This requires a refresh to fix.

**Comment by dev7355608** [comment]
This error message looks like it would be unrelated to PV (PV is probably listed as a false-positive). Did you confirm that there's no error without PV?

**Comment by dev7355608** [comment]
I tried to reproduce it, but I was unable to. I assume it is unrelated to PV. If you can me detailed instructions on how to reproduce this in a new scene, I'll reopen this issue.
