### ISSUE TITLE
LightingLayerPF2e is failing when loading world

### ISSUE THREAD

**Issue by lslavkov** [dev7355608/perfect-vision#244]
As title says, I am having issues to open my world. When active scene is loading it gives me error LightinigLayerPF2e is not working.

Error log: 
```
TypeError: Cannot read properties of undefined (reading 'darknessLevel')
[Detected 3 packages: perfect-vision, lib-wrapper, system:pf2e]
    at LightingLayerPF2e.🎁LightingLayer.prototype.refresh#perfect-vision (lighting.js:133:42)
    at Wrapper.🎁call_wrapper [as call_wrapper] (libWrapper-wrapper.js:595:14)
    at LightingLayerPF2e.🎁LightingLayer.prototype.refresh#0 (libWrapper-wrapper.js:189:20)
    at LightingLayerPF2e.refresh (main.bundle.js:1:453431)
    at PerceptionManager._update (foundry.js:33351:47)
    at PerceptionManager.update (foundry.js:33263:10)
    at PerceptionManager.initialize (foundry.js:33272:17)
    at Canvas._initialize (foundry.js:20277:21)
    at async Canvas.draw (foundry.js:20134:7)
    at async Canvas.🎁Canvas.prototype.draw#perfect-vision (canvas.js:415:9)
    at async ScenePF2e.view (foundry.js:17859:7)
    at async Game.initializeCanvas (foundry.js:5677:20)
    at async Game.setupGame (foundry.js:5548:5)
    at async Game._initializeGameView (foundry.js:6514:5)
    at async Game.initialize (foundry.js:5431:5)
onError @ foundry.js:319
```

**Comment by dev7355608** [comment]
Is Perfect Vision up to date (v3.7.33)?

**Comment by dev7355608** [comment]
Any error messages above this one (or other error messages in general)? I cannot reproduce it.

**Comment by dev7355608** [comment]
Should you have just updated from FVTT v8 to v9, follow these instructions:
> **Caching Issues**
>
> There is a known issue for users updating from V8 to V9 related to caching which causes some errors, UI oddities, and trouble with canvas rendering which can be addressed quickly and immediately without support assistance. If a simple CTRL+F5 (CMD+SHIFT+F5 for Mac) does not resolve the issue:
>
> Steps to fix caching issues:
> 1. Open the DevTools using the F12 key (or cmd-shift-i for macOS)
> 2. Click the settings ⚙ icon
> 3. Below the heading 'network' check the checkbox for 'Disable Cache (when DevTools is open)
> 4. Leave the DevTools window open and refresh (f5) the Foundry VTT window
>
> *Note: Firefox users will see this checkbox under 'Advanced Settings' -> 'Disable HTTP Cache (when toolbox is open)'*

**Comment by lslavkov** [comment]
It seems worked by just removing cache. Closing this ticket.
