### ISSUE TITLE
[BUG] Latest version causing issues with levels module

### ISSUE THREAD

**Issue by kuchrk24** [dev7355608/perfect-vision#248]
Foundry v9.269
Perfect Vision v 3.8.2

Trying to move between levels with perfect vision resulting in console error and a blank screen when a token selected. Works as expected with perfect vision disabled.

![image](https://user-images.githubusercontent.com/74018852/165371913-27a3e1e7-972a-4be6-a4a9-54477c5d0ce0.png)

pixi-cullable.js:5 Uncaught TypeError: Cannot read properties of undefined (reading 'x')
[Detected 2 packages: perfect-vision, lib-wrapper]
    at e.PIXI.Rectangle.intersects (pixi-cullable.js:5:35)
    at LightSource._pv_drawMask (index.js:600:48)
    at SightLayer.🎁SightLayer.prototype.refresh#perfect-vision (sight.js:184:24)
    at Wrapper.🎁call_wrapper [as call_wrapper] (libWrapper-wrapper.js:595:14)
    at SightLayer.🎁SightLayer.prototype.refresh#0 (libWrapper-wrapper.js:189:20)
    at PerceptionManager._update (foundry.js:33354:41)
    at foundry.js:33326:54

**Comment by dev7355608** [comment]
Thanks for the report. Fixed in 3.8.3.
