### ISSUE TITLE
Error in images loading

### ISSUE THREAD

**Issue by urko-vi** [dev7355608/perfect-vision#252]
I got this error:

```
foundry.js:319 TypeError: Cannot read properties of undefined (reading 'removeChildren')
[Detected 1 package: perfect-vision]
    at SightLayer.initializeSources (foundry.js:30266:19)
    at PerceptionManager._update (foundry.js:33344:44)
    at PerceptionManager.update (foundry.js:33263:10)
    at PerceptionManager.initialize (foundry.js:33272:17)
    at Canvas._initialize (foundry.js:20277:21)
    at async Canvas.draw (foundry.js:20134:7)
    at async Canvas.🎁Canvas.prototype.draw#perfect-vision (canvas.js:345:9)
    at async Scene.view (foundry.js:17859:7)
    at async Game.initializeCanvas (foundry.js:5677:20)
    at async Game.setupGame (foundry.js:5548:5)
    at async Game._initializeGameView (foundry.js:6514:5)
    at async Game.initialize (foundry.js:5431:5)
```

And I only see a black background image.

**Comment by dev7355608** [comment]
This is probably a cache issue. Follow the following instructions; CTRL+F5 should to the trick:

> **Caching Issues**
>
> There is a known issue for users updating from V8 to V9 related to caching which causes some errors, UI oddities, and trouble with canvas rendering which can be addressed quickly and immediately without support assistance. If a simple CTRL+F5 (CMD+SHIFT+F5 for Mac) does not resolve the issue:
>
> Steps to fix caching issues:
> 1. Open the DevTools using the F12 key (or cmd-shift-i for macOS)
> 2. Click the settings ⚙ icon
> 3. Below the heading 'network' check the checkbox for 'Disable Cache (when DevTools is open)
> 4. Leave the DevTools window open and refresh (f5) the Foundry VTT window
>
> *Note: Firefox users will see this checkbox under 'Advanced Settings' -> 'Disable HTTP Cache (when toolbox is open)'*

**Comment by urko-vi** [comment]
It’s not. I have already done before posting (I’m web developer). I’ve put the console error trace.

**Comment by dev7355608** [comment]
Then you must have an outdated version of PV installed. Uninstall and reinstall PV to force it to the latest version. Maybe it got stuck on an old version somehow.

**Comment by urko-vi** [comment]
That has worked. Thanks.
