### ISSUE TITLE
this._recycleVisionContainer is not a function Error

### ISSUE THREAD

**Issue by eclay1819** [dev7355608/perfect-vision#257]
I've found an odd bug. Currently running version 3.9.7 of Perfect Vision and Version 9 - Build 269 of FoundryVTT.

When transitioning between two scenes, i.e. transition from scene 1 to scene 2, then back to scene 1, scene 2 just loads a blank screen - refreshing via F5 or the browser button fixes it. I found this error in the console when this happens (text and screenshot below).

I tried reinstalling the module, rebooting the server, etc. to no effect. Any help would be appreciated! My only player told me he had the same issue.

Uncaught (in promise) TypeError: this._recycleVisionContainer is not a function
[Detected 3 packages: lichtgeschwindigkeit, perfect-vision, lib-wrapper]
    at fog.js:57:50
    at Array.forEach (<anonymous>)
    at SightLayer.commitFog (fog.js:57:32)
    at Wrapper.🎁call_wrapped [as call_wrapped] (libWrapper-wrapper.js:511:22)
    at SightLayer.🎁SightLayer.prototype.commitFog#perfect-vision (sight.js:452:9)
    at Wrapper.🎁call_wrapper [as call_wrapper] (libWrapper-wrapper.js:620:16)
    at SightLayer.🎁SightLayer.prototype.commitFog#0 (libWrapper-wrapper.js:189:20)
    at SightLayer.tearDown (foundry.js:30229:12)
    at Wrapper.🎁call_wrapped [as call_wrapped] (libWrapper-wrapper.js:511:22)
    at SightLayer.🎁SightLayer.prototype.tearDown#perfect-vision (sight.js:73:22)
    at Wrapper.🎁call_wrapper [as call_wrapper] (libWrapper-wrapper.js:620:16)
    at SightLayer.🎁SightLayer.prototype.tearDown#0 (libWrapper-wrapper.js:189:20)
    at Canvas.tearDown (foundry.js:20029:15)
    at async Canvas.draw (foundry.js:20059:23)
    at async Canvas.🎁Canvas.prototype.draw#perfect-vision (canvas.js:415:9)
    at async Scene.view (foundry.js:17859:7)

![image](https://user-images.githubusercontent.com/57675836/170168382-d852a10c-d1fa-4228-8acd-27d920f25ba0.png)

**Comment by eclay1819** [comment]
Confirmed that fixed it - I appreciate the help!
