### ISSUE TITLE
Error when open drawing configuration page

### ISSUE THREAD

**Issue by sanguaire** [dev7355608/perfect-vision#273]
Hi, 

Browser: Brave
Foundry version: 10.283

when I try to open a drawing property page I get the following console error

`foundry.js:711 TypeError: Cannot read properties of undefined (reading 'value')
[Detected 3 packages: LockView, perfect-vision, lib-wrapper]
    at closeDrawingConfigApp (drawingConfig.js:51:70)
    at Object.fn (lockview.js:37:46)
    at #call (foundry.js:688:20)
    at Hooks.call (foundry.js:670:38)
    at DrawingConfig.close (foundry.js:5383:13)
    at DrawingConfig.close (foundry.js:6084:18)
    at DrawingConfig.close (foundry.js:6197:17)
    at DrawingConfig.close (foundry.js:69216:17)
    at 🎁call_wrapped [as call_wrapped] (libWrapper-wrapper.js:511:22)
    at 🎁DrawingConfig.prototype.close#perfect-vision (drawing.js:110:26)
    at 🎁call_wrapper [as call_wrapper] (libWrapper-wrapper.js:620:16)
    at 🎁DrawingConfig.prototype.close#0 (libWrapper-wrapper.js:189:20)
    at foundry.js:13344:45
    at Array.forEach (<anonymous>)
    at DrawingDocument._onDelete (foundry.js:13344:30)
    at DrawingDocument._onDelete (foundry.js:12198:11)
    at ClientDatabaseBackend.callback (foundry.js:12875:11)
    at foundry.js:12858:43
    at Array.map (<anonymous>)
    at ClientDatabaseBackend._handleDeleteEmbeddedDocuments (foundry.js:12858:33)
    at ClientDatabaseBackend._deleteEmbeddedDocuments (foundry.js:12750:17)
    at async DrawingDocument.deleteDocuments (commons.js:5697:23)`

and the property page don't open.

After deactivating perfect vision I can open the property page.

**Comment by dev7355608** [comment]
I'm unable to reproduce it. Make sure Lock View and PV are up to date and that only PV and Lockview (and libwrapper) are active. Then try to reproduce it and give me a step-by-step description. Thanks!

**Comment by WilStead** [comment]
Not sure if this is the same issue or a different one, but I am also unable to open the drawing property page with Perfect Vision enabled.

Foundry version 10.284
Foundry desktop client
Windows 11 x64

The error below occurs when the modules Advanced Drawing Tools, libWrapper, and Perfect Vision are enabled.
If only Advanced Drawing Tools and/or libWrapper are enabled, no error occurs and the property page opens.
If only libWrapper and Perfect Vision are enabled, no error occurs and the property page opens.

Tested with these module versions:
- Advanced Drawing Tools 2.0.2
- libWrapper 1.12.7.2
- Perfect Vision 4.0.2

Game System: DnD5e - Fifth Edition System 2.0.2

Error:
```
foundry.js:711 TypeError: Cannot read properties of null (reading 'checked')
[Detected 3 packages: advanced-drawing-tools, lib-wrapper, perfect-vision]
    at 🎁DrawingConfig.prototype._getSubmitData#advanced-drawing-tools (config.js:8:83)
    at 🎁call_wrapper [as call_wrapper] (libWrapper-wrapper.js:620:16)
    at 🎁DrawingConfig.prototype._getSubmitData#perfect-vision (drawing.js:10:26)
    at 🎁call_wrapper [as call_wrapper] (libWrapper-wrapper.js:620:16)
    at 🎁DrawingConfig.prototype._getSubmitData#0 (libWrapper-wrapper.js:189:20)
    at #saveFormData (helper.js:262:34)
    at LightingConfigHelper.updateFormFields (helper.js:220:27)
    at updateForm (drawing.js:117:26)
    at 🎁DrawingConfig.prototype._renderInner#perfect-vision (drawing.js:91:13)
    at async DrawingConfig._render (foundry.js:4965:19)
    at async DrawingConfig._render (foundry.js:5684:5)
onError @ foundry.js:711
🎁call_wrapped @ libWrapper-wrapper.js:511
🎁Hooks.onError#lib-wrapper @ listeners.js:137
🎁Hooks.onError#0 @ libWrapper-wrapper.js:187
(anonymous) @ foundry.js:4920
Promise.catch (async)
render @ foundry.js:4918
render @ foundry.js:6254
_onClickLeft2 @ foundry.js:25230
callback @ foundry.js:26244
_handleClickLeft2 @ foundry.js:26458
_handleMouseDown @ foundry.js:26420
a.emit @ index.js:181
r.dispatchEvent @ interaction.min.mjs:8
r.processPointerDown @ interaction.min.mjs:8
t.recursiveFindHit @ interaction.min.mjs:8
t.recursiveFindHit @ interaction.min.mjs:8
t.recursiveFindHit @ interaction.min.mjs:8
t.recursiveFindHit @ interaction.min.mjs:8
t.recursiveFindHit @ interaction.min.mjs:8
t.recursiveFindHit @ interaction.min.mjs:8
t.findHit @ interaction.min.mjs:8
r.processInteractive @ interaction.min.mjs:8
r.onPointerDown @ interaction.min.mjs:8
```

**Comment by dev7355608** [comment]
I assume this was caused by an outdated version. I wasn't able to reproduce it with the most recent version of Lock View. But should this still be an issue, don't hesitate to reopen this issue.
