### ISSUE TITLE
Perfect Vision in combination with Advanced Drawing Tools breaks the Drawing config 

### ISSUE THREAD

**Issue by dev7355608** [dev7355608/perfect-vision#277]
Reported by @WilStead.

---

Foundry version 10.284
Foundry desktop client
Windows 11 x64

The error below occurs when the modules Advanced Drawing Tools, libWrapper, and Perfect Vision are enabled.
If only Advanced Drawing Tools and/or libWrapper are enabled, no error occurs and the property page opens.
If only libWrapper and Perfect Vision are enabled, no error occurs and the property page opens.

Tested with these module versions:
- Advanced Drawing Tools 2.0.2
- libWrapper 1.12.7.2
- Perfect Vision 4.0.2

Game System: DnD5e - Fifth Edition System 2.0.2

Error:
```
foundry.js:711 TypeError: Cannot read properties of null (reading 'checked')
[Detected 3 packages: advanced-drawing-tools, lib-wrapper, perfect-vision]
    at 🎁DrawingConfig.prototype._getSubmitData#advanced-drawing-tools (config.js:8:83)
    at 🎁call_wrapper [as call_wrapper] (libWrapper-wrapper.js:620:16)
    at 🎁DrawingConfig.prototype._getSubmitData#perfect-vision (drawing.js:10:26)
    at 🎁call_wrapper [as call_wrapper] (libWrapper-wrapper.js:620:16)
    at 🎁DrawingConfig.prototype._getSubmitData#0 (libWrapper-wrapper.js:189:20)
    at #saveFormData (helper.js:262:34)
    at LightingConfigHelper.updateFormFields (helper.js:220:27)
    at updateForm (drawing.js:117:26)
    at 🎁DrawingConfig.prototype._renderInner#perfect-vision (drawing.js:91:13)
    at async DrawingConfig._render (foundry.js:4965:19)
    at async DrawingConfig._render (foundry.js:5684:5)
onError @ foundry.js:711
🎁call_wrapped @ libWrapper-wrapper.js:511
🎁Hooks.onError#lib-wrapper @ listeners.js:137
🎁Hooks.onError#0 @ libWrapper-wrapper.js:187
(anonymous) @ foundry.js:4920
Promise.catch (async)
render @ foundry.js:4918
render @ foundry.js:6254
_onClickLeft2 @ foundry.js:25230
callback @ foundry.js:26244
_handleClickLeft2 @ foundry.js:26458
_handleMouseDown @ foundry.js:26420
a.emit @ index.js:181
r.dispatchEvent @ interaction.min.mjs:8
r.processPointerDown @ interaction.min.mjs:8
t.recursiveFindHit @ interaction.min.mjs:8
t.recursiveFindHit @ interaction.min.mjs:8
t.recursiveFindHit @ interaction.min.mjs:8
t.recursiveFindHit @ interaction.min.mjs:8
t.recursiveFindHit @ interaction.min.mjs:8
t.recursiveFindHit @ interaction.min.mjs:8
t.findHit @ interaction.min.mjs:8
r.processInteractive @ interaction.min.mjs:8
r.onPointerDown @ interaction.min.mjs:8
```

**Comment by dev7355608** [comment]
Thanks for the report, @WilStead! Fixed in 4.0.3.
