### ISSUE TITLE
Token Configuration popup will not close

### ISSUE THREAD

**Issue by Kallaide** [dev7355608/perfect-vision#308]
### Expected Behavior

When clicking on Close or Update Token, the popup should close

### Current Behavior

Clicking on either Update Token or the Close button does absolutely nothing and the only way to clear the popup is to refresh the webpage.

### Steps to Reproduce

1. Open Character Sheet and go to Token Configuration
2. Try and close Token Configuration

### Context

Here are the Console Errors I'm getting when clicking on the following buttons:

x Close button:
`Uncaught (in promise) TypeError: Cannot assign to read only property '_id' of object '#<TokenDocument5e>'`
`[Detected 2 packages: perfect-vision, lib-wrapper]`
`    at SchemaField._cleanType (commons.js:4028:20)`
`    at SchemaField.clean (commons.js:3760:19)`
`    at TokenDocument5e.cleanData (commons.js:5368:26)`
`    at TokenDocument5e.cleanData (commons.js:10279:29)`
`    at TokenDocument5e.validate (commons.js:5466:48)`
`    at TokenDocument5e.updateSource (commons.js:5549:12)`
`    at TokenConfig.previewChanges (light.js:26:25)`
`    at 🎁call_wrapper [as call_wrapper] (libWrapper-wrapper.js:591:14)`
`    at 🎁TokenConfig.prototype._previewChanges#0 (libWrapper-wrapper.js:189:20)`
`    at TokenConfig._resetPreview (foundry.js:70588:10)`
`    at TokenConfig.close (foundry.js:70510:32)`
`    at Object.onclick (foundry.js:5290:29)`
`    at HTMLAnchorElement.<anonymous> (foundry.js:5198:16)`
`    at HTMLAnchorElement.dispatch (jquery.min.js:2:43064)`
`    at y.handle (jquery.min.js:2:41048)`

Apply button:
`TypeError: Cannot assign to read only property '_id' of object '#<TokenDocument5e>'`
`    at SchemaField._cleanType (commons.js:4028:20)`
`    at SchemaField.clean (commons.js:3760:19)`
`    at TokenDocument5e.cleanData (commons.js:5368:26)`
`    at TokenDocument5e.cleanData (commons.js:10279:29)`
`    at TokenDocument5e.validate (commons.js:5466:48)`
`    at TokenDocument5e.updateSource (commons.js:5549:12)`
`    at TokenConfig.previewChanges (light.js:26:25)`
`    at 🎁call_wrapper [as call_wrapper] (libWrapper-wrapper.js:591:14)`
`    at 🎁TokenConfig.prototype._previewChanges#0 (libWrapper-wrapper.js:189:20)`
`    at TokenConfig._resetPreview (foundry.js:70588:10)`
`    at TokenConfig._updateObject (foundry.js:70595:10)`
`    at TokenConfig._onSubmit (foundry.js:5874:18)`
`    at HTMLButtonElement.<anonymous> (applyButton.js:8:17)`
`    at HTMLButtonElement.dispatch (jquery.min.js:2:43064)`
`    at y.handle (jquery.min.js:2:41048)`
`_onSubmit @ foundry.js:5877`
`await in _onSubmit (async)`
`(anonymous) @ applyButton.js:8`
`dispatch @ jquery.min.js:2`
`y.handle @ jquery.min.js:2`

Update Token button:
`TypeError: Cannot assign to read only property '_id' of object '#<TokenDocument5e>'`
`    at SchemaField._cleanType (commons.js:4028:20)`
`    at SchemaField.clean (commons.js:3760:19)`
`    at TokenDocument5e.cleanData (commons.js:5368:26)`
`    at TokenDocument5e.cleanData (commons.js:10279:29)`
`    at TokenDocument5e.validate (commons.js:5466:48)`
`    at TokenDocument5e.updateSource (commons.js:5549:12)`
`    at TokenConfig.previewChanges (light.js:26:25)`
`    at 🎁call_wrapper [as call_wrapper] (libWrapper-wrapper.js:591:14)`
`    at 🎁TokenConfig.prototype._previewChanges#0 (libWrapper-wrapper.js:189:20)`
`    at TokenConfig._resetPreview (foundry.js:70588:10)`
`    at TokenConfig._updateObject (foundry.js:70595:10)`
`    at TokenConfig._onSubmit (foundry.js:5874:18)`
`_onSubmit @ foundry.js:5877`

### Version

v4.0.48

### Foundry VTT Version

v10.288

### Operating System

Docker / Unraid

### Browser / App

Chrome

### Game System

dnd5e

**Comment by Kallaide** [comment]
Le sigh... Of course, it was updated, and I didn't check that first. Error is not present in v4.0.49
